# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_d_norm <- function(x, mu, sigma) {
    .Call('mfa_log_d_norm', PACKAGE = 'mfa', x, mu, sigma)
}

log_sum_exp <- function(x) {
    .Call('mfa_log_sum_exp', PACKAGE = 'mfa', x)
}

r_bernoulli_mat <- function(pi) {
    .Call('mfa_r_bernoulli_mat', PACKAGE = 'mfa', pi)
}

calculate_nuk <- function(y, pst, c, tau, theta, tau_k, which_l) {
    .Call('mfa_calculate_nuk', PACKAGE = 'mfa', y, pst, c, tau, theta, tau_k, which_l)
}

calculate_lamk <- function(chi, tau, pst, which_l) {
    .Call('mfa_calculate_lamk', PACKAGE = 'mfa', chi, tau, pst, which_l)
}

sample_k <- function(y, pst, c, tau, theta, tau_k, which_l) {
    .Call('mfa_sample_k', PACKAGE = 'mfa', y, pst, c, tau, theta, tau_k, which_l)
}

calculate_nuc <- function(y, pst, k, tau, eta, tau_c, which_l) {
    .Call('mfa_calculate_nuc', PACKAGE = 'mfa', y, pst, k, tau, eta, tau_c, which_l)
}

calculate_lamc <- function(tau, tau_c, N) {
    .Call('mfa_calculate_lamc', PACKAGE = 'mfa', tau, tau_c, N)
}

sample_c <- function(y, pst, k, tau, eta, tau_c, which_l, N) {
    .Call('mfa_sample_c', PACKAGE = 'mfa', y, pst, k, tau, eta, tau_c, which_l, N)
}

pst_update_par <- function(y, c, k, r, gamma, tau) {
    .Call('mfa_pst_update_par', PACKAGE = 'mfa', y, c, k, r, gamma, tau)
}

sample_pst <- function(y, c, k, r, gamma, tau) {
    .Call('mfa_sample_pst', PACKAGE = 'mfa', y, c, k, r, gamma, tau)
}

tau_params <- function(y, c, k, gamma, pst, alpha, beta) {
    .Call('mfa_tau_params', PACKAGE = 'mfa', y, c, k, gamma, pst, alpha, beta)
}

sample_tau <- function(y, c, k, gamma, pst, alpha, beta) {
    .Call('mfa_sample_tau', PACKAGE = 'mfa', y, c, k, gamma, pst, alpha, beta)
}

calculate_pi <- function(y, c, k, pst, tau, eta, tau_c, collapse, log_w, log_result) {
    .Call('mfa_calculate_pi', PACKAGE = 'mfa', y, c, k, pst, tau, eta, tau_c, collapse, log_w, log_result)
}

sample_x <- function(x, is_dropout, c, k, gamma, pst, tau, lambda) {
    .Call('mfa_sample_x', PACKAGE = 'mfa', x, is_dropout, c, k, gamma, pst, tau, lambda)
}

